# vim:fileencoding=utf-8:foldmethod=marker:foldlevel=99

# Fonts {{{
font_family family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 11.0
# }}}

# Mouse {{{
copy_on_select yes
#: mouse-hide-while-typing
mouse_hide_wait -1
# }}}

# Appearance {{{
# Text cursor customization{{{
cursor_trail 3
#: cursor-invert-fg-bg
cursor none
# }}}

# Tab bar{{{
# tab_bar_style powerline
tab_title_template "{title}{fmt.bold}{'  ' if num_windows > 1 and layout_name == 'stack' else ''}"
# }}}

# Background{{{
background_image ~/Documents/Image/backgroud/wall-1.jpg
background_image_layout cscaled
background_image_linear yes
background_tint 0.95
# }}}
# }}}

# Keybindings {{{
kitty_mod ctrl+shift
map kitty_mod+enter launch --cwd=current
map kitty_mod+space toggle_layout stack
map kitty_mod+p command_palette
map kitty_mod+r load_config_file
# map kitty_mod+L goto_session
map kitty_mod+alt+l goto_session ~/.config/kitty/sessions
# }}}

# Window layout {{{
remember_window_size  yes
initial_window_height 30c
initial_window_width  90c

enabled_layouts tall:bias=70;full_size=2,stack
hide_window_decorations yes
# }}}

# Misc{{{
enable_audio_bell no
# scrollback_pager nvim --clean -c 'set clipboard+=unnamedplus' -c 'set eventignore=FileType' +'nnoremap q ZQ' +'call nvim_open_term(0, {})' +'set nomodified nolist'  +'$' -
scrollback_pager nvim --clean -c 'lua dofile("$HOME/.config/kitty/kitty_scrollback.lua")(INPUT_LINE_NUMBER, CURSOR_LINE, CURSOR_COLUMN)' -

auto_reload_config -1
# startup_session ./sessions/dev.kitty-session
# }}}
