font_family       JetBrainsMono Nerd Font
font_size 12.0
cursor_trail 3
cursor none
copy_on_select yes
enable_audio_bell no
enabled_layouts tall:bias=70;full_size=2,stack
hide_window_decorations yes
background_image /home/lauv/Documents/Image/backgroud/Lake.png
background_image_layout cscaled
background_image_linear yes
background_tint 0.95
kitty_mod ctrl+shift
map kitty_mod+enter launch --cwd=current
map kitty_mod+space toggle_layout stack
# map kitty_mod+r load_config_file
tab_title_template "{title}{fmt.bold}{'  ' if num_windows > 1 and layout_name == 'stack' else ''}"

remember_window_size  yes
initial_window_height 30c
initial_window_width  90c
