font_family       JetBrainsMono Nerd Font
font_size 12.0
cursor_trail 1
copy_on_select yes
enable_audio_bell no
enabled_layouts tall:bias=70;full_size=2,stack
hide_window_decorations yes
background_image /home/lauv/Documents/Image/backgroud/Lake.png
background_image_layout cscaled
background_image_linear yes
background_tint 0.95
kitty_mod ctrl+shift
map kitty_mod+enter launch --cwd=current
map ctrl+shift+space toggle_layout stack
