# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
# "$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [
	{ on = "!", run  = 'shell "$SHELL" --block', desc = "Open shell here"}, # Unix
  # { on = "!", run  = 'shell "powershell.exe" --block', desc = "Open PowerShell here"} # Windows
]
